/* Generated by BIN2S - please don't edit directly */
	.section .rodata.default_shbin, "a"
	.balign 4
	.global default_shbin
default_shbin:
	.byte  68, 86, 76, 66,  1,  0,  0,  0,120,  0,  0,  0, 68, 86, 76, 80
	.byte   0,  0,  0,  0, 40,  0,  0,  0,  7,  0,  0,  0, 68,  0,  0,  0
	.byte   5,  0,  0,  0,108,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
	.byte   0,  0,  0,  0,  0,  0,  2,  8,  1, 16,  2,  8,  2, 32,  2,  8
	.byte   3, 48,  2,  8,  4, 16, 32, 76,  4, 32, 64, 76,  0,  0,  0,136
	.byte 104,195,  6,  0,  0,  0,  0,  0,100,195,  6,  0,  0,  0,  0,  0
	.byte  98,195,  6,  0,  0,  0,  0,  0, 97,195,  6,  0,  0,  0,  0,  0
	.byte 111,  3,  0,  0,  0,  0,  0,  0, 68, 86, 76, 69,  2, 16,  0,  0
	.byte   0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0
	.byte  64,  0,  0,  0,  0,  0,  0,  0, 64,  0,  0,  0,  0,  0,  0,  0
	.byte  64,  0,  0,  0,  3,  0,  0,  0, 88,  0,  0,  0,  1,  0,  0,  0
	.byte  96,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0, 15,  0,  0,  0
	.byte   2,  0,  1,  0, 15,  0,  0,  0,  3,  0,  2,  0, 15,  0,  0,  0
	.byte   0,  0,  0,  0, 16,  0, 19,  0,109,118,112, 95,109, 97,116,  0

	.global default_shbin_end
default_shbin_end:



#if defined(__linux__) && defined(__ELF__)
.section .note.GNU-stack,"",%progbits
#endif